# Generated by Django 6.0.6 on 2026-07-08 18:01

from django.db import migrations, models
from django.db.models import F


def backfill_subtotals(apps, schema_editor):
    OrderItem = apps.get_model('supermarket', 'OrderItem')
    OrderItem.objects.update(subtotal=F('price') * F('quantity'))


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RunPython(backfill_subtotals, migrations.RunPython.noop),
    ]
